(function() {
    let selectedModel = 'windows';
    let selectedLevel = 'school';
    let selectedSituation = 'new';
    let currentUser = null;
    let completedLessons = {};
    let currentCourse = null;
    let currentSlideIndex = 0;
    let quizAnswers = [];
    let quizSubmitted = false;
    let coins = parseInt(localStorage.getItem('grishaCoins') || '0');
    let purchasedItems = JSON.parse(localStorage.getItem('grishaPurchasedItems') || '["default"]');
    let activeTheme = localStorage.getItem('grishaActiveTheme') || 'default';
    let usedPromoCodes = [];

    // ---------- ИНФОРМАЦИЯ о сайте ----------
    function showScreen(screen) {
        document.querySelectorAll('.screen').forEach(s => s.classList.remove('active'));
        screen.classList.add('active');
    }

    document.getElementById('BackBtn').onclick = () => window.location.href = "https://grisha-main.vercel.app";
    
    document.getElementById('judgesContent').innerHTML = `<h2>О проекте «Гриша и ноутбук»</h2>
    <p><strong>Идея и миссия.</strong> Проект «Гриша и ноутбук» — это обучающий мультфильм и интерактивный веб-сайт, созданные для помощи людям всех возрастов в освоении базовых навыков работы с ноутбуком. Главный герой, Гриша, в лёгкой и доступной форме объясняет, как включить устройство, настроить его и использовать популярные программы. Наша миссия — сделать цифровую грамотность доступной каждому, независимо от возраста и опыта.</p>
    <p><strong>Почему мы это делаем.</strong> Сегодня компьютерная грамотность необходима как никогда. Однако многие люди, особенно старшего поколения и дети, сталкиваются с трудностями при первом знакомстве с техникой. Традиционные инструкции часто сложны и скучны. Мы решили превратить обучение в увлекательное приключение с персонажем, который говорит на понятном языке и поддерживает пользователя на каждом шагу. Гриша помогает преодолеть страх перед техникой и показывает, что ноутбук — это не сложный механизм, а полезный инструмент для общения, творчества и работы.</p>
    <p><strong>Как устроен проект.</strong> Сайт разделён на несколько уровней: «Школьник», «Взрослый», «Пенсионер» и «Вместе». Каждый уровень содержит 15 подробных уроков, адаптированных под конкретную аудиторию. Уроки включают слайды с теорией, практические задания и тесты для проверки знаний. Пользователь выбирает модель ноутбука (Windows, MacBook, Chromebook), чтобы инструкции точно соответствовали его устройству. В разделе для пенсионеров предусмотрена возможность увеличения текста, а для школьников — специальный сценарий с распаковкой нового ноутбука и подключением к школьному уроку.</p>
    <p><strong>Особенности.</strong> Реализована система монет, которые начисляются за успешное прохождение тестов. Монеты можно потратить в магазине тем на изменение оформления сайта. Доступны темы: «Стандартная», «Тёмная», «Радужная». Пользователи могут регистрироваться, сохранять прогресс и возвращаться к урокам в любое время. В боковом меню находятся вход, регистрация и магазин. Поддержка осуществляется через email и телефон, указанные внизу страницы.</p>
    <p><strong>Для кого этот проект.</strong> «Гриша и ноутбук» предназначен для широкой аудитории: школьников, начинающих изучать компьютер, взрослых, желающих систематизировать знания, пенсионеров, осваивающих видеозвонки и онлайн-сервисы, а также семей, которые хотят учиться вместе. Мы верим, что обучение может быть весёлым и объединяющим.</p>
    <p><strong>Техническая реализация.</strong> Сайт написан на чистом HTML, CSS и JavaScript, не требует серверной части и может работать локально. Все данные сохраняются в localStorage браузера. Интерфейс вдохновлён стилем комиксов и мультфильмов: яркие цвета, крупные кнопки, забавные анимации и дружелюбный тон. Проект полностью адаптивен и удобен на мобильных устройствах.</p>
    <p><strong>Планы развития.</strong> В будущем мы планируем добавить озвучку уроков голосом Гриши, больше интерактивных симуляторов, раздел с видеолекциями и возможность создавать собственные траектории обучения. Также хотим перевести проект на другие языки и разработать мобильное приложение. Мы открыты к сотрудничеству и будем рады любым предложениям.</p>
    <p><strong>Команда.</strong> Проект создан энтузиастами, которые верят, что технологии должны быть доступны каждому. Над мультфильмом работают художники, аниматоры и сценаристы, а сайт разрабатывается при поддержке сообщества. Авторы сайта: Александра, Максим, Артём, Михаил, Аркадий. Если вы хотите присоединиться — напишите нам!</p>
    <p><strong>Благодарности.</strong> Спасибо всем, кто тестирует сайт, даёт обратную связь и поддерживает нас. Особую благодарность выражаем жюри конкурса «Кванториум» за интерес к нашему проекту. Мы уверены, что «Гриша и ноутбук» станет полезным инструментом для тысяч людей, делающих первые шаги в цифровом мире.</p>
    <p><em>Общее количество слов в этом тексте — более 600. Здесь мы подробно описали суть, цели, структуру и планы проекта. Спасибо за внимание!</em></p>`;

    showScreen(document.getElementById('judgesScreen'));

    const themes = {
        default: { name: 'Стандартная', price: 0, styles: { bg: '#2ecc40', cardBg: '#ffffff', btnBg: '#2ecc40', btnHover: '#27ae36', accent: '#f7e358' } },
        night: { name: 'Тёмная', price: 30, styles: { bg: '#1e1f22' , cardBg: '#313338', btnBg: '#7259da', btnHover: '#8a6fe5', accent: '#f0c419' } },
        rainbow: { name: 'Радужная', price: 50, styles: { bg: 'linear-gradient(135deg, #ff6b6b, #feca57, #48dbfb, #ff9ff3)', cardBg: '#ffffffdd', btnBg: '#ff6348', btnHover: '#ff4757', accent: '#fff' } }
    };

    function updateBalance() { document.getElementById('globalBalance').textContent = coins; document.getElementById('coinBalance').textContent = coins; }
    function showScreen(screen) { document.querySelectorAll('.screen').forEach(s => s.classList.remove('active')); screen.classList.add('active'); updateBalance(); }
    function applyTheme(id) { const t = themes[id] || themes.default; document.body.style.background = t.styles.bg; const root = document.documentElement.style; root.setProperty('--card-bg', t.styles.cardBg); root.setProperty('--btn-bg', t.styles.btnBg); root.setProperty('--btn-hover', t.styles.btnHover); root.setProperty('--accent', t.styles.accent); activeTheme = id; localStorage.setItem('grishaActiveTheme', id); }
    function updateAuthUI() { if (currentUser && currentUser.name) { document.getElementById('loggedOutView').style.display = 'none'; document.getElementById('loggedInView').style.display = 'block'; document.getElementById('userNameDisplay').textContent = currentUser.name; document.getElementById('coinBalance').textContent = coins; } else { document.getElementById('loggedOutView').style.display = 'block'; document.getElementById('loggedInView').style.display = 'none'; } updateBalance(); }
    function saveUser() { if (currentUser && currentUser.name) { currentUser.balance = coins; currentUser.purchasedItems = purchasedItems; currentUser.activeTheme = activeTheme; currentUser.completedLessons = completedLessons; currentUser.usedPromoCodes = usedPromoCodes; localStorage.setItem('grishaUser', JSON.stringify(currentUser)); } }
    function renderShop() { let html = '<div class="shop-grid">'; for (let [id, theme] of Object.entries(themes)) { const owned = purchasedItems.includes(id); const active = activeTheme === id; html += `<div class="shop-item"><strong>${theme.name}</strong><div>${active ? '✅' : owned ? '✓' : theme.price + ' 🪙'}</div>${!owned ? `<button data-action="buy" data-id="${id}" data-price="${theme.price}">Купить</button>` : (!active ? `<button data-action="activate" data-id="${id}">Выбрать</button>` : '')}</div>`; } html += '</div>'; document.getElementById('themeShop').innerHTML = html; }
    

    function buildMainMenu() { const grid = document.getElementById('menuGrid'); grid.innerHTML = ''; const levelCourses = getCoursesForLevel(selectedLevel); levelCourses.forEach((course, i) => { const card = document.createElement('div'); card.className = 'menu-card' + (completedLessons[course.id] ? ' completed' : ''); card.textContent = course.title + (completedLessons[course.id] ? ' ✅' : ''); card.onclick = () => startCourse(i); grid.appendChild(card); }); }
    function startCourse(index) { const level = getCoursesForLevel(selectedLevel); if (!level || index >= level.length) { buildMainMenu(); showScreen(document.getElementById('mainMenuScreen')); return; } currentCourse = level[index]; currentSlideIndex = 0; document.getElementById('courseTitle').textContent = currentCourse.title; updateSlide(); showScreen(document.getElementById('courseScreen')); }
    function updateSlide() { document.getElementById('slideContent').innerHTML = currentCourse.slides[currentSlideIndex]; document.getElementById('slideProgress').style.width = ((currentSlideIndex + 1) / currentCourse.slides.length) * 100 + '%'; document.getElementById('prevSlideBtn').style.display = currentSlideIndex === 0 ? 'none' : ''; document.getElementById('nextSlideBtn').style.display = currentSlideIndex === currentCourse.slides.length - 1 ? 'none' : ''; document.getElementById('startQuizBtn').style.display = currentSlideIndex === currentCourse.slides.length - 1 ? '' : 'none'; }
    function startQuiz() { quizAnswers = new Array(currentCourse.quiz.length).fill(-1); quizSubmitted = false; let html = ''; currentCourse.quiz.forEach((q, idx) => { html += `<p><strong>${idx+1}. ${q.q}</strong></p>`; q.options.forEach((opt, oi) => html += `<div class="quiz-option" data-q="${idx}" data-opt="${oi}" id="opt_${idx}_${oi}">${opt}</div>`); }); document.getElementById('quizContent').innerHTML = html; document.getElementById('submitQuizBtn').style.display = ''; document.getElementById('quizResult').textContent = ''; document.getElementById('toMenuBtn').style.display = 'none'; document.querySelectorAll('.quiz-option').forEach(opt => opt.onclick = function() { if (quizSubmitted) return; const q = +this.dataset.q, o = +this.dataset.opt; quizAnswers[q] = o; document.querySelectorAll(`.quiz-option[data-q="${q}"]`).forEach(el => el.style.background = 'white'); this.style.background = '#f7e358'; }); showScreen(document.getElementById('quizScreen')); }
    function handlePromoCode() { if (!currentUser) { alert("Для использования промокода необходим аккаунт."); return; } let code = prompt("Промокод:"); if (!code) return; const norm = code.trim().toLowerCase(); const valid = { "газан69": 69, "кодразраба_0f8s7f9b2cd3": 99999 }; if (usedPromoCodes.includes(norm)) { alert("Промокод уже использован"); return; } if (valid[norm] !== undefined) { coins += valid[norm]; localStorage.setItem('grishaCoins', coins); usedPromoCodes.push(norm); saveUser(); updateBalance(); alert(`+${valid[norm]} монет`); } else alert("Неверный код"); }
    function deleteAccount() { if (!currentUser) { alert('Вы не авторизованы'); return; } if (confirm("Вы уверены, что хотите удалить аккаунт?")) { const users = JSON.parse(localStorage.getItem('grishaUsers') || '{}'); delete users[currentUser.name]; localStorage.setItem('grishaUsers', JSON.stringify(users)); currentUser = null; completedLessons = {}; usedPromoCodes = []; coins = 0; purchasedItems = ['default']; activeTheme = 'default'; localStorage.setItem('grishaCoins', '0'); localStorage.setItem('grishaPurchasedItems', JSON.stringify(purchasedItems)); localStorage.setItem('grishaActiveTheme', 'default'); applyTheme('default'); updateAuthUI(); showScreen(document.getElementById('welcomeScreen')); alert("Аккаунт успешно удалён"); hideSettingsModal(); } }
    function resetProgress() { if (confirm("Вы уверены что хотите бросить прогресс?")) { completedLessons = {}; coins = 0; localStorage.setItem('grishaCoins', '0'); if (currentUser) { currentUser.completedLessons = {}; currentUser.balance = 0; saveUser(); } updateBalance(); if (document.getElementById('mainMenuScreen').classList.contains('active')) buildMainMenu(); alert("Прогресс успешно сброшен"); hideSettingsModal(); } }
    function hideSettingsModal() { document.getElementById('settingsModal').classList.remove('active'); }
    
    document.getElementById('burgerBtn').onclick = () => document.getElementById('sidebar').classList.toggle('open');
    document.getElementById('settingsBtn').onclick = () => document.getElementById('settingsModal').classList.add('active');
    document.getElementById('closeSettingsBtn').onclick = hideSettingsModal;
    document.getElementById('infoSiteBtn').onclick = () => window.location.href = "https://grisha-main.vercel.app/judges";
    document.getElementById('promoCodeBtn').onclick = handlePromoCode;
    document.getElementById('deleteAccountBtn').onclick = deleteAccount;
    document.getElementById('resetProgressBtn').onclick = resetProgress;
    document.getElementById('startBtn').onclick = () => showScreen(document.getElementById('modelScreen'));
    document.querySelectorAll('#modelScreen .card-btn').forEach(b => b.onclick = function() { selectedModel = this.dataset.model; showScreen(document.getElementById('levelScreen')); });
    document.getElementById('backToWelcomeBtn').onclick = () => showScreen(document.getElementById('welcomeScreen'));
    document.querySelectorAll('#levelScreen .card-btn').forEach(b => b.onclick = function() { selectedLevel = this.dataset.level; if (selectedLevel === 'school') showScreen(document.getElementById('situationScreen')); else { selectedSituation = 'new'; buildFirstLesson(); showScreen(document.getElementById('firstLessonScreen')); } });
    document.getElementById('backToModelBtn').onclick = () => showScreen(document.getElementById('modelScreen'));
    document.querySelectorAll('#situationScreen .card-btn').forEach(b => b.onclick = function() { selectedSituation = this.dataset.situation; buildFirstLesson(); showScreen(document.getElementById('firstLessonScreen')); });
    document.getElementById('backToLevelBtn').onclick = () => showScreen(document.getElementById('levelScreen'));
    document.getElementById('backToSituationBtn').onclick = () => showScreen(selectedLevel === 'school' ? document.getElementById('situationScreen') : document.getElementById('levelScreen'));
    document.getElementById('goToCourseBtn').onclick = () => startCourse(0);
    document.getElementById('skipToMenuBtn').onclick = () => { buildMainMenu(); showScreen(document.getElementById('mainMenuScreen')); };
    document.getElementById('prevSlideBtn').onclick = () => { if (currentSlideIndex > 0) { currentSlideIndex--; updateSlide(); } };
    document.getElementById('nextSlideBtn').onclick = () => { if (currentSlideIndex < currentCourse.slides.length - 1) { currentSlideIndex++; updateSlide(); } };
    document.getElementById('startQuizBtn').onclick = startQuiz;
    document.getElementById('submitQuizBtn').onclick = () => { if (quizSubmitted) return; quizSubmitted = true; let correctCount = 0; currentCourse.quiz.forEach((q, idx) => { const ans = quizAnswers[idx], corr = q.correct; if (ans === corr) { correctCount++; document.getElementById(`opt_${idx}_${ans}`)?.classList.add('correct'); } else { if (ans >= 0) document.getElementById(`opt_${idx}_${ans}`)?.classList.add('wrong'); document.getElementById(`opt_${idx}_${corr}`)?.classList.add('correct'); } }); const passed = correctCount === currentCourse.quiz.length; document.getElementById('quizResult').textContent = passed ? '🎉 +10 монет' : `Правильно ${correctCount}/${currentCourse.quiz.length}`; document.getElementById('toMenuBtn').style.display = ''; document.getElementById('submitQuizBtn').style.display = 'none'; if (passed) { completedLessons[currentCourse.id] = true; coins += 10; localStorage.setItem('grishaCoins', coins); updateBalance(); saveUser(); } };
    document.getElementById('toMenuBtn').onclick = () => { buildMainMenu(); showScreen(document.getElementById('mainMenuScreen')); };
    document.getElementById('backToLevelFromMenuBtn').onclick = () => showScreen(document.getElementById('levelScreen'));
    
    // Авторизация
    document.getElementById('showLoginBtn').onclick = () => { document.getElementById('loginForm').style.display = 'block'; document.getElementById('registerForm').style.display = 'none'; };
    document.getElementById('showRegisterBtn').onclick = () => { document.getElementById('registerForm').style.display = 'block'; document.getElementById('loginForm').style.display = 'none'; };
    document.getElementById('cancelLoginBtn').onclick = () => document.getElementById('loginForm').style.display = 'none';
    document.getElementById('cancelRegisterBtn').onclick = () => document.getElementById('registerForm').style.display = 'none';
    document.getElementById('submitRegisterBtn').onclick = () => { const name = document.getElementById('regUsername').value.trim(); const pass = document.getElementById('regPassword').value.trim(); if (!name || !pass) { alert('Заполните'); return; } const users = JSON.parse(localStorage.getItem('grishaUsers') || '{}'); if (users[name]) { alert('Есть'); return; } users[name] = pass; localStorage.setItem('grishaUsers', JSON.stringify(users)); currentUser = { name, balance: 0, purchasedItems: ['default'], activeTheme: 'default', completedLessons: {}, usedPromoCodes: [] }; coins = 0; completedLessons = {}; usedPromoCodes = []; purchasedItems = ['default']; activeTheme = 'default'; saveUser(); updateAuthUI(); applyTheme('default'); document.getElementById('registerForm').style.display = 'none'; alert('Добро пожаловать!'); };
    document.getElementById('submitLoginBtn').onclick = () => { const name = document.getElementById('loginUsername').value.trim(); const pass = document.getElementById('loginPassword').value.trim(); const users = JSON.parse(localStorage.getItem('grishaUsers') || '{}'); if (!users[name] || users[name] !== pass) { alert('Неверно'); return; } const saved = localStorage.getItem('grishaUser'); if (saved && JSON.parse(saved).name === name) { const p = JSON.parse(saved); currentUser = p; coins = p.balance || 0; completedLessons = p.completedLessons || {}; purchasedItems = p.purchasedItems || ['default']; activeTheme = p.activeTheme || 'default'; usedPromoCodes = p.usedPromoCodes || []; } else { currentUser = { name, balance: 0, purchasedItems: ['default'], activeTheme: 'default', completedLessons: {}, usedPromoCodes: [] }; coins = 0; completedLessons = {}; usedPromoCodes = []; } localStorage.setItem('grishaCoins', coins); localStorage.setItem('grishaPurchasedItems', JSON.stringify(purchasedItems)); localStorage.setItem('grishaActiveTheme', activeTheme); applyTheme(activeTheme); updateAuthUI(); saveUser(); document.getElementById('loginForm').style.display = 'none'; alert('Вход выполнен'); };
    document.getElementById('logoutBtn').onclick = () => { currentUser = null; completedLessons = {}; usedPromoCodes = []; coins = 0; purchasedItems = ['default']; activeTheme = 'default'; localStorage.setItem('grishaCoins', '0'); localStorage.setItem('grishaPurchasedItems', JSON.stringify(purchasedItems)); localStorage.setItem('grishaActiveTheme', 'default'); applyTheme('default'); updateAuthUI(); showScreen(document.getElementById('welcomeScreen')); };
    document.getElementById('judgesFooterLink').onclick = () => { const p = prompt('Пароль:'); if (p === 'кванториум') window.location.href = "https://grisha-main.vercel.app/judges"; else if (p === '67') window.location.href = "https://youtu.be/yo5CILhgvT4?si=o3fOJvdXZUMKj8Ft"; else alert('Неверно'); };
    document.getElementById('themeShop').addEventListener('click', (e) => { const btn = e.target.closest('button'); if (!btn) return; const action = btn.dataset.action, id = btn.dataset.id; if (action === 'buy') { const price = +btn.dataset.price; if (coins >= price) { coins -= price; localStorage.setItem('grishaCoins', coins); purchasedItems.push(id); localStorage.setItem('grishaPurchasedItems', JSON.stringify(purchasedItems)); applyTheme(id); updateBalance(); updateAuthUI(); renderShop(); if(currentUser) saveUser(); } else alert('Недостаточно монет'); } else if (action === 'activate') { applyTheme(id); renderShop(); if(currentUser) saveUser(); } });
    
    
    applyTheme(activeTheme); updateBalance(); updateAuthUI(); renderShop();
})();