(function() {
    // ======================= РАСШИРЕННЫЕ КУРСЫ: ПО 10 УРОКОВ В КАЖДУЮ КАТЕГОРИЮ =======================
    const courses = {
        school: [
            { id: 'paint', title: '🎨 Paint', slides: ['<p>Знакомство с Paint. Откройте: Пуск → Paint. Кисти, фигуры, палитра.</p><p>Практика: нарисуйте домик.</p>', '<p>Сохранение: Файл → Сохранить как → PNG.</p>'], quiz: [{ q: 'Где найти Paint?', options: ['Пуск → Paint', 'Рабочий стол', 'Интернет'], correct: 0 }, { q: 'Как залить цветом?', options: ['Кисть', 'Ведёрко', 'Ластик'], correct: 1 }] },
            { id: 'word', title: '📝 Microsoft Word', slides: ['<p>Текстовый редактор Word: шрифт, вставка картинок.</p>'], quiz: [{ q: 'Как изменить шрифт?', options: ['Выделить → выбрать шрифт', 'Нажать Enter'], correct: 0 }, { q: 'Сочетание сохранить?', options: ['Ctrl+Z', 'Ctrl+S', 'Ctrl+C'], correct: 1 }] },
            { id: 'powerpoint', title: '📽️ PowerPoint', slides: ['<p>Создание презентации, слайды, анимация, F5 показ.</p>'], quiz: [{ q: 'Кнопка показа слайдов?', options: ['F5', 'Delete'], correct: 0 }, { q: 'Расширение файла PowerPoint?', options: ['.docx', '.xlsx', '.pptx'], correct: 2 }] }, 
            { id: 'internet_safety', title: '🔒 Безопасность', slides: ['<p>Не доверяйте фишингу, ставьте сложные пароли, двойные домены в сайтах бывают опасны.</p>'], quiz: [{ q: 'Что такое фишинг?', options: ['Рыбалка', 'Кража данных', 'Вредоносная программа'], correct: 1 }, { q: 'Какой сайт достовернее?', options: ['girsha-main.vecrel.app', 'vk.com.ag', 'max.ru'], correct: 2 }] }, 
            { id: 'files_folders', title: '📁 Файлы и папки', slides: ['<p>Создание, копирование Ctrl+C, вставка Ctrl+V, вырезать Ctrl+X</p>'], quiz: [{ q: 'Горячая клавиша копирования?', options: ['Ctrl+C', 'Ctrl+V', 'Ctrl+X'], correct: 0 }, { q: 'Кнопка которая удаляет слова и переносит их в буфер обмена?', options: ['Ctrl+X', 'Ctrl+N', 'Win+L'], correct: 0 }] },  
            { id: 'shortcuts', title: '⌨️ Горячие клавиши', slides: ['<p>Ctrl+Z отмена, Ctrl+A выделить всё, Alt+Tab переключение окон.</p>', '<p>Win+D показать рабочий стол, Ctrl+Shift+Esc диспетчер задач.</p>'], quiz: [{ q: 'Какая комбинация отменяет действие?', options: ['Ctrl+Z', 'Ctrl+Y', 'Ctrl+X'], correct: 0 }, { q: 'Что делает Win+D?', options: ['Сворачивает всё', 'Открывает браузер', 'Копирует'], correct: 0 }] },
            { id: 'browser_secrets', title: '🌐 Браузер: советы', slides: ['<p>Вкладки: Ctrl+T новая, Ctrl+W закрыть, Ctrl+Shift+T восстановить.</p><p>Закладки: Ctrl+D добавить в избранное.</p>'], quiz: [{ q: 'Как открыть новую вкладку?', options: ['Ctrl+T', 'Ctrl+N', 'Ctrl+Shift+T'], correct: 0 }, { q: 'Как добавить выделенные слова или буквы в избранное?', options: ['Ctrl+Alt+Del', 'Ctrl+D', 'Ctrl+T'], correct: 1 }] }, 
            { id: 'typing', title: '✍️ Набор текста', slides: ['<p>Слепая печать, сайты клавиатурные тренажёры. Shift для заглавных.</p>'], quiz: [{ q: 'Как написать заглавную букву?', options: ['Shift + буква', 'Caps Lock', 'Alt'], correct: 0 }, { q: 'Как напечатать восклицательный знак?', options: ['Shift+1', 'Shift+2', 'Shift+3'], correct: 0 }] }, 
            { id: 'calculator', title: '🧮 Калькулятор ПК', slides: ['<p>Пуск → Калькулятор. Режимы: обычный, инженерный. История вычислений.</p>'], quiz: [{ q: 'Где открыть калькулятор?', options: ['Пуск → Калькулятор', 'Рабочий стол'], correct: 0 }, { q: 'Какого режима не существует?', options: ['Инженерный', 'Программист', 'Учёный'], correct: 2 }] }, 
            { id: 'screenshot', title: '📸 Скриншоты', slides: ['<p>Print Screen — скриншот всего экрана. Alt+Print Screen — активное окно. Ножницы (Snipping Tool).</p>'], quiz: [{ q: 'Кнопка для скриншота окна?', options: ['Alt+Print Screen', 'Print Screen', 'Ctrl+P'], correct: 0 }, { q: 'Кнопка для скриншота всего экрана?', options: ['PrintScreen', 'CapsLock', 'Win'], correct: 0 }] }, 
        ],
        adult: [
            { id: 'excel', title: '📊 Excel', slides: ['<p><strong>Excel — электронные таблицы.</strong> Откройте: Пуск → Excel. Сетка из ячеек. Вводите текст, числа, формулы.</p>', '<p><strong>Ввод данных.</strong> Кликните в ячейку → печатайте. Enter — вниз, Tab — вправо.</p>', '<p><strong>Формулы.</strong> Начните со знака =. =2+2 — сложение. =СУММ(A1:A10) — сумма диапазона.</p>', '<p><strong>Диаграммы.</strong> Выделите данные → Вставка → выберите тип диаграммы.</p>', '<p><strong>Сохранение.</strong> Файл → Сохранить как → имя → Сохранить.</p>'], quiz: [{ q: 'С чего начать формулу?', options: ['Со знака =', 'С буквы', 'С пробела'], correct: 0 }, { q: 'Как вставить диаграмму?', options: ['Вставка → Диаграмма', 'Нарисовать', 'Нельзя'], correct: 0 }] },
            { id: 'email', title: '✉️ Электронная почта', slides: ['<p><strong>Регистрация почты.</strong> Зайдите на mail.ru или gmail.com. Нажмите «Создать аккаунт».</p>', '<p><strong>Отправка письма.</strong> Войдите в почту → «Написать письмо». Введите адрес получателя, тему, текст. Прикрепите файл (скрепка).</p>', '<p><strong>Чтение писем.</strong> Кликните на письмо в папке «Входящие». Ответить — кнопка «Ответить».</p>', '<p><strong>Безопасность.</strong> Никогда не переходите по ссылкам от незнакомцев. Не сообщайте пароль.</p>'], quiz: [{ q: 'Как прикрепить файл к письму?', options: ['Нажать на скрепку', 'Скопировать текст', 'Отправить без файла'], correct: 0 }, { q: 'Что делать с подозрительным письмом?', options: ['Не открывать ссылки', 'Ответить', 'Переслать друзьям'], correct: 0 }] },
            { id: 'online_banking', title: '🏦 Онлайн-банкинг', slides: ['<p><strong>Мобильный банк.</strong> Скачайте приложение Сбербанк, Тинькофф или ВТБ. Войдите по логину/паролю.</p>', '<p><strong>Платежи.</strong> Выберите «Платежи» → «Кому» → введите номер телефона или карты → сумму → подтвердить.</p>', '<p><strong>Проверка истории.</strong> Вкладка «История» показывает все операции. Проверяйте регулярно.</p>', '<p><strong>Безопасность.</strong> Никому не говорите SMS-коды. Не заходите в банк по ссылкам из писем.</p>'], quiz: [{ q: 'Как оплатить услугу?', options: ['Платежи → выбрать получателя', 'Написать в чат', 'Позвонить в банк'], correct: 0 }, { q: 'Можно ли сообщать код из SMS?', options: ['Нет, никогда', 'Да, если просит банк', 'Только друзьям'], correct: 0 }] },
            { id: 'cloud_storage', title: '☁️ Облачные хранилища', slides: ['<p><strong>Google Диск.</strong> Зайдите на drive.google.com. Войдите под своей почтой.</p>', '<p><strong>Загрузка файлов.</strong> Нажмите «Создать» или перетащите файл мышкой.</p>', '<p><strong>Доступ по ссылке.</strong> ПКМ на файле → «Получить ссылку». Установите права «Просмотр» или «Редактирование».</p>', '<p><strong>Синхронизация.</strong> Скачайте приложение «Backup and Sync» — файлы с компьютера автоматически загружаются в облако.</p>'], quiz: [{ q: 'Как поделиться файлом?', options: ['ПКМ → Получить ссылку', 'Отправить по почте', 'Скопировать название'], correct: 0 }, { q: 'Где хранятся облачные файлы?', options: ['На серверах Google', 'На флешке', 'В компьютере друга'], correct: 0 }] }, 
            { id: 'excel_charts', title: '📈 Excel: диаграммы', slides: ['<p><strong>Типы диаграмм.</strong> Гистограмма – сравнение, круговая – доли.</p><p>Выделите данные → Вставка → Рекомендуемые диаграммы.</p>'], quiz: [{ q:'Какая диаграмма для долей?', options:['Круговая','Линейная','Гистограмма'], correct:0},{ q:'Как вставить диаграмму?', options:['Вставка → Диаграмма','Файл → Печать','Данные → Сортировка'], correct:0}] },
            { id: 'email_filters', title: '📁 Email: папки и фильтры', slides: ['<p><strong>Создание папок.</strong> Почта → Создать папку «Работа», «Личное».</p><p><strong>Фильтры.</strong> Настройки → Фильтры: письма от начальника сразу в папку Работа.</p>'], quiz: [{ q:'Зачем нужны фильтры?', options:['Автоматически сортировать письма','Удалить все письма','Сменить пароль'], correct:0},{ q:'Как создать папку?', options:['В настройках почты','На рабочем столе','В проводнике'], correct:0}] },
            { id: 'bank_payments', title: '💳 Платежи и автоплатежи', slides: ['<p><strong>Автоплатеж.</strong> Коммунальные услуги списываются автоматически каждый месяц.</p><p><strong>QR-код.</strong> В приложении банка наведите камеру на QR для оплаты.</p>'], quiz: [{ q:'Что такое автоплатеж?', options:['Регулярный автоматический платёж','Разовый перевод','Онлайн-кредит'], correct:0},{ q:'Как оплатить по QR?', options:['Навести камеру в приложении','Ввести номер карты','Позвонить оператору'], correct:0}] },
            { id: 'cloud_collab', title: '🤝 Совместная работа в облаке', slides: ['<p><strong>Одновременное редактирование.</strong> Google Документы: открыть доступ, несколько человек могут писать текст вместе.</p>','<p><strong>История версий.</strong> Файл → История версий → вернуться к старой версии.</p>'], quiz: [{ q:'Где посмотреть историю версий?', options:['Файл → История','Правка → Отменить','Вставка → Комментарий'], correct:0},{ q:'Как пригласить коллегу?', options:['Кнопка «Настройки доступа»','Скачать файл','Отправить письмо'], correct:0}] },
            { id: 'word_templates', title: '📄 Word: шаблоны', slides: ['<p><strong>Готовые шаблоны.</strong> Файл → Создать → выбрать «Резюме», «Письмо».</p><p><strong>Сохранение своего шаблона.</strong> Файл → Сохранить как → тип «Шаблон Word».</p>'], quiz: [{ q:'Где найти готовый шаблон резюме?', options:['Файл → Создать','Вставка → Рисунок','Рецензирование'], correct:0},{ q:'Какой формат у шаблона Word?', options:['.dotx','.docx','.pdf'], correct:0}] },
            { id: 'task_planner', title: '📅 Планировщик задач', slides: ['<p><strong>Microsoft To Do.</strong> Создайте список дел на сегодня. Установите напоминание.</p>','<p><strong>Календарь Outlook.</strong> Планируйте встречи и приглашайте участников.</p>'], quiz: [{ q:'Как создать напоминание?', options:['Выбрать дату и время','Написать письмо','Сохранить файл'], correct:0},{ q:'Где хранятся задачи?', options:['В облаке Microsoft','На флешке','В папке Загрузки'], correct:0}] }
        ],
        senior: [
            { id: 'zoom', title: '📹 Zoom', slides: ['<p><strong>Zoom — видеозвонки.</strong> Откройте браузер → zoom.us/download → Загрузить. Установите программу.</p>', '<p><strong>Вход в конференцию.</strong> Нажмите «Войти в конференцию» → введите ID и пароль.</p>', '<p><strong>Управление.</strong> Внизу панель: микрофон (вкл/выкл), камера, чат.</p>', '<p><strong>Чат и реакции.</strong> Кнопка «Чат» → напишите сообщение. «Участники» → «Поднять руку».</p>', '<p><strong>Выход.</strong> Красная кнопка «Выйти».</p>'], quiz: [{ q: 'Где скачать Zoom?', options: ['zoom.us/download', 'В магазине', 'Не знаю'], correct: 0 }, { q: 'Как включить микрофон?', options: ['Нажать на значок микрофона', 'Крикнуть', 'Никак'], correct: 0 }] },
            { id: 'skype', title: '💬 Skype', slides: ['<p><strong>Skype — альтернатива Zoom.</strong> Скачайте с skype.com. Установите и войдите (или создайте учётную запись).</p>', '<p><strong>Звонок.</strong> Найдите контакт в поиске → нажмите на видео/аудио вызов.</p>', '<p><strong>Чат.</strong> Напишите текст, отправьте смайлик, прикрепите фото.</p>', '<p><strong>Демонстрация экрана.</strong> Во время звонка нажмите «…» → «Демонстрация экрана».</p>'], quiz: [{ q: 'Как позвонить по видео?', options: ['Найти контакт → значок камеры', 'Отправить письмо', 'Набрать номер'], correct: 0 }, { q: 'Что показывает демонстрация экрана?', options: ['Ваш рабочий стол', 'Ваше лицо', 'Только чат'], correct: 0 }] },
            { id: 'gosuslugi', title: '🏛️ Госуслуги', slides: ['<p><strong>Регистрация на Госуслугах.</strong> Зайдите на gosuslugi.ru. Нажмите «Зарегистрироваться». Введите СНИЛС, паспорт, телефон.</p>', '<p><strong>Подтверждение личности.</strong> Можно в МФЦ, заказным письмом или через банк (Тинькофф, Сбер).</p>', '<p><strong>Получение услуги.</strong> Выберите нужную услугу (загранпаспорт, справки, запись к врачу) → заполните заявление → отправьте.</p>', '<p><strong>Уведомления.</strong> Статус заявления придёт на email или в личный кабинет.</p>'], quiz: [{ q: 'Что нужно для регистрации?', options: ['СНИЛС и паспорт', 'Только телефон', 'Зарплата'], correct: 0 }, { q: 'Где подтвердить личность?', options: ['В МФЦ', 'В магазине', 'По телефону'], correct: 0 }] },
            { id: 'whatsapp', title: '📱 WhatsApp', slides: ['<p><strong>Установка WhatsApp.</strong> Найдите в Play Market или App Store. Установите, подтвердите номер телефона.</p>', '<p><strong>Отправка сообщений.</strong> Выберите контакт → напишите текст, отправьте смайлик, фото, голосовое сообщение.</p>', '<p><strong>Звонки.</strong> Нажмите на значок телефона или камеры вверху чата. Бесплатно по интернету.</p>', '<p><strong>Группы.</strong> Создайте группу для семьи: «Меню» → «Новая группа» → добавьте участников.</p>'], quiz: [{ q: 'Что нужно для регистрации?', options: ['Номер телефона', 'Пароль от почты', 'QR-код'], correct: 0 }, { q: 'Как позвонить?', options: ['Нажать значок телефона', 'Написать "Позвони"', 'Отправить письмо'], correct: 0 }] }, 
            { id: 'zoom_settings', title: '⚙️ Zoom: настройки', slides: ['<p><strong>Фон и шум.</strong> Настройки → Фон и фильтры → размытие фона. Подавление шума.</p><p><strong>Запись встречи.</strong> Кнопка Запись → облако или компьютер.</p>'], quiz: [{ q:'Где включить размытие фона?', options:['Настройки → Фон','Чат','Участники'], correct:0},{ q:'Как записать встречу?', options:['Кнопка Запись','Сфотографировать экран','Никак'], correct:0}] },
            { id: 'skype_chat', title: '💬 Skype: чат и файлы', slides: ['<p><strong>Отправка фото.</strong> Кнопка «Прикрепить» → Выбрать изображение.</p><p><strong>Голосовые сообщения.</strong> Зажмите микрофон, записывайте, отпустите.</p>'], quiz: [{ q:'Как отправить фото в Skype?', options:['Прикрепить файл','Написать слово "фото"','Позвонить'], correct:0},{ q:'Что такое голосовое сообщение?', options:['Аудиозапись','Видеозвонок','Текст'], correct:0}] },
            { id: 'gosuslugi_doctor', title: '🏥 Госуслуги: запись к врачу', slides: ['<p><strong>Запись через Госуслуги.</strong> Услуги → Здоровье → Запись к врачу → выбрать специалиста и время.</p><p><strong>Отмена записи.</strong> Мои записи → Отменить.</p>'], quiz: [{ q:'Где на Госуслугах записаться к врачу?', options:['Услуги → Здоровье','Каталог → Спорт','Мои налоги'], correct:0},{ q:'Можно ли отменить запись?', options:['Да, в разделе Мои записи','Нет','Только по телефону'], correct:0}] },
            { id: 'whatsapp_voice', title: '🎤 WhatsApp: голосовые и стикеры', slides: ['<p><strong>Голосовое сообщение:</strong> зажмите значок микрофона, говорите, отпустите.</p><p><strong>Стикеры и гифки.</strong> Нажмите на смайлик → стикеры → выбрать.</p>'], quiz: [{ q:'Как отправить голосовое?', options:['Зажать микрофон','Нажать камеру','Написать текст'], correct:0},{ q:'Где найти стикеры?', options:['В меню смайликов','В настройках','В чате после текста'], correct:0}] },
            { id: 'online_shopping', title: '🛍️ Покупки в интернете', slides: ['<p><strong>Ozon/Wildberries.</strong> Найдите товар, добавьте в корзину, выберите оплату картой.</p><p><strong>Доставка.</strong> Пункт выдачи или курьер. Отслеживайте в приложении.</p>'], quiz: [{ q:'Как оплатить заказ?', options:['Картой онлайн','Наличными курьеру','Оба варианта'], correct:2},{ q:'Где посмотреть статус доставки?', options:['В приложении магазина','На почте','В СМС'], correct:0}] },
            { id: 'youtube_search', title: '📺 YouTube: поиск и плейлисты', slides: ['<p><strong>Поиск видео.</strong> Введите тему в строку поиска. Фильтры: по дате, длительности.</p><p><strong>Плейлисты.</strong> Сохраните любимые видео в «Сохранить» → создать плейлист.</p>'], quiz: [{ q:'Как найти видео за прошлый месяц?', options:['Фильтры → Дата','Поиск → подробно','Настройки'], correct:0},{ q:'Для чего нужен плейлист?', options:['Группировать видео','Удалить видео','Скачать видео'], correct:0}] }
        ],
        together: [
            { id: 'paint_family', title: '🎨 Рисуем вместе', slides: ['<p><strong>Совместное рисование в Paint.</strong> Сядьте вдвоём. Откройте Paint: Пуск → Paint.</p>', '<p><strong>Тема рисунка.</strong> Договоритесь, что рисовать: дом, семья, природа.</p>', '<p><strong>Процесс.</strong> Один рисует основу, второй добавляет детали.</p>', '<p><strong>Сохранение.</strong> Файл → Сохранить как → «Наш рисунок» → Сохранить.</p>', '<p><strong>Совет.</strong> Устройте конкурс рисунков!</p>'], quiz: [{ q: 'Как открыть Paint?', options: ['Пуск → Paint', 'Через интернет', 'Никак'], correct: 0 }, { q: 'Что делать, если ошиблись?', options: ['Ctrl+Z', 'Выкинуть компьютер в окно', 'Плакать'], correct: 0 }] },
            { id: 'family_calendar', title: '📅 Семейный календарь', slides: ['<p><strong>Google Календарь.</strong> Зайдите на calendar.google.com. Войдите под общей учётной записью.</p>', '<p><strong>Создание события.</strong> Кликните на день → укажите название, время, описание. Добавьте напоминание.</p>', '<p><strong>Общий доступ.</strong> Настройки календаря → «Доступ» → включите «Делиться со всеми».</p>', '<p><strong>Планирование.</strong> Отмечайте дни рождения, походы к врачу, отпуска всей семьи.</p>'], quiz: [{ q: 'Как создать событие?', options: ['Кликнуть на день', 'Нажать Esc', 'Перезагрузить'], correct: 0 }, { q: 'Зачем общий календарь?', options: ['Чтобы видеть планы семьи', 'Для паролей', 'Для игр'], correct: 0 }] },
            { id: 'together_presentation', title: '👥 Совместная презентация', slides: ['<p><strong>PowerPoint Online.</strong> Откройте office.com, войдите. Создайте презентацию и нажмите «Поделиться».</p>', '<p><strong>Редактирование вдвоём.</strong> Отправьте ссылку второму человеку. Вы можете работать одновременно: один вставляет картинки, другой пишет текст.</p>', '<p><strong>Комментарии.</strong> Выделите текст → «Вставить комментарий». Обсуждайте изменения.</p>', '<p><strong>Скачивание.</strong> Файл → Сохранить как → PPTX.</p>'], quiz: [{ q: 'Как пригласить второго?', options: ['Позвать за компьютер', 'Поделиться ссылкой', 'Отправить по факсу'], correct: 1 }, { q: 'Что такое комментарий?', options: ['Новый слайд', 'Исправление ошибки', 'Заметка для обсуждения'], correct: 2 }] },
            { id: 'family_budget', title: '💰 Семейный бюджет в Excel', slides: ['<p><strong>Таблица доходов и расходов.</strong> Создайте столбцы: Дата, Статья, Доход, Расход.</p>', '<p><strong>Формула итога.</strong> =СУММ(столбец Доход) — общий доход. =СУММ(столбец Расход) — расходы.</p>', '<p><strong>Совместное заполнение.</strong> Сохраните файл в облаке (Google Диск), чтобы оба могли редактировать.</p>', '<p><strong>График.</strong> Выделите данные → Вставка → диаграмма для наглядности.</p>'], quiz: [{ q: 'Какая формула для суммы?', options: ['=ИТОГ', '=СУММ()', '=ПЛЮС()'], correct: 1 }, { q: 'Где удобно хранить общий файл?', options: ['В облаке', 'На флешке', 'На рабочем столе одного ПК'], correct: 0 }] }, 
            { id: 'family_album', title: '🖼️ Семейный фотоальбом', slides: ['<p><strong>Google Фото.</strong> Загрузите фотографии с телефона в общий альбом.</p><p><strong>Комментарии к фото.</strong> Добавляйте подписи и лайки.</p>'], quiz: [{ q:'Где создать общий альбом?', options: ['Google Фото','Paint','Word'], correct: 0},{ q:'Можно ли комментировать фото?', options:['Да','Нет','Только владельцу'], correct:0}] },
            { id: 'calendar_advanced', title: '📆 Общий календарь (продвинутый)', slides: ['<p><strong>Приглашение по email.</strong> Создайте событие, добавьте гостей — они получат уведомление.</p><p><strong>Повтор событий.</strong> Каждый понедельник → тренировка.</p>'], quiz: [{ q:'Как пригласить гостя?', options: ['Добавить email в событие','Позвонить','Написать в чат'], correct:0},{ q:'Где настроить повтор?', options: ['В параметрах события','В настройках аккаунта','В теме письма'], correct: 0 }] },
            { id: 'online_presentation', title: '🌐 Презентация онлайн вместе', slides: ['<p><strong>Canva для двоих.</strong> Поделитесь ссылкой на дизайн. Оба могут менять слайды.</p><p><strong>Голосовой чат.</strong> Обсуждайте изменения прямо в браузере.</p>'], quiz: [{ q:'Какая программа позволяет совместно делать презентации?', options:['Canva','Блокнот','Калькулятор'], correct:0},{ q:'Что нужно для совместной работы?', options: ['Ссылка-приглашение','Один компьютер','Флешка'], correct: 0 }] },
            { id: 'budget_categories', title: '📊 Бюджет: категории расходов', slides: ['<p><strong>Категории.</strong> Еда, транспорт, развлечения. В Excel создайте выпадающий список.</p><p><strong>Сводная таблица.</strong> Легко посмотреть сумму по категориям.</p>'], quiz: [{ q:'Как создать выпадающий список?', options: ['Данные → Проверка данных','Вставка → Список','Формулы → Сумм'], correct:0},{ q:'Зачем категории?', options: ['Анализировать куда уходят деньги','Чтобы сложнее','Для красоты'], correct: 0 }] },
            { id: 'draw_online', title: '🎨 Рисование вместе онлайн', slides: ['<p><strong>Aggie.io</strong> — бесплатный сервис. Создайте комнату и рисуйте одновременно с другом.</p><p><strong>Слои.</strong> Каждый рисует на своем слое, не мешая другому.</p>'], quiz: [{ q:'Как начать рисовать вдвоем?', options: ['Создать комнату и дать ссылку','Открыть Paint','Сфотографировать'], correct:0},{ q:'Что такое слой?', options: ['Отдельный уровень рисования','Кисть','Ластик'], correct:0}] },
            { id: 'travel_planning', title: '✈️ Планирование отпуска', slides: ['<p><strong>Google Таблицы.</strong> Создайте список городов, билетов, отелей.</p><p><strong>Обсуждение.</strong> Комментарии к ячейкам: «Давай забронируем этот отель?»</p>'], quiz: [{ q:'Где удобно планировать вместе?', options: ['Google Таблицы','YouTube','Почта'], correct: 0 },{ q:'Как оставить заметку?', options: ['ПКМ → Комментарий','Написать в документ','Позвонить'], correct: 0 }] }
        ]
    };
    function getCoursesForLevel(level) { return courses[level] || []; }

    let selectedModel = 'windows';
    let selectedLevel = 'school';
    let selectedSituation = 'new';
    let currentUser = null;
    let completedLessons = {};
    let currentCourse = null;
    let currentSlideIndex = 0;
    let quizAnswers = [];
    let quizSubmitted = false;
    let coins = parseInt(localStorage.getItem('grishaCoins') || '0');
    let purchasedItems = JSON.parse(localStorage.getItem('grishaPurchasedItems') || '["default"]');
    let activeTheme = localStorage.getItem('grishaActiveTheme') || 'default';
    let usedPromoCodes = [];

    const themes = {
        default: { name: 'Стандартная', price: 0, styles: { bg: '#2ecc40', cardBg: '#ffffff', btnBg: '#2ecc40', btnHover: '#27ae36', accent: '#f7e358' } },
        night: { name: 'Тёмная', price: 30, styles: { bg: '#1e1f22' , cardBg: '#313338', btnBg: '#7259da', btnHover: '#8a6fe5', accent: '#f0c419' } },
        rainbow: { name: 'Радужная', price: 50, styles: { bg: 'linear-gradient(135deg, #ff6b6b, #feca57, #48dbfb, #ff9ff3)', cardBg: '#ffffffdd', btnBg: '#ff6348', btnHover: '#ff4757', accent: '#fff' } }
    };

    function updateBalance() { document.getElementById('globalBalance').textContent = coins; document.getElementById('coinBalance').textContent = coins; }
    function showScreen(screen) { document.querySelectorAll('.screen').forEach(s => s.classList.remove('active')); screen.classList.add('active'); updateBalance(); }
    function applyTheme(id) { const t = themes[id] || themes.default; document.body.style.background = t.styles.bg; const root = document.documentElement.style; root.setProperty('--card-bg', t.styles.cardBg); root.setProperty('--btn-bg', t.styles.btnBg); root.setProperty('--btn-hover', t.styles.btnHover); root.setProperty('--accent', t.styles.accent); activeTheme = id; localStorage.setItem('grishaActiveTheme', id); }
    function updateAuthUI() { if (currentUser && currentUser.name) { document.getElementById('loggedOutView').style.display = 'none'; document.getElementById('loggedInView').style.display = 'block'; document.getElementById('userNameDisplay').textContent = currentUser.name; document.getElementById('coinBalance').textContent = coins; } else { document.getElementById('loggedOutView').style.display = 'block'; document.getElementById('loggedInView').style.display = 'none'; } updateBalance(); }
    function saveUser() { if (currentUser && currentUser.name) { currentUser.balance = coins; currentUser.purchasedItems = purchasedItems; currentUser.activeTheme = activeTheme; currentUser.completedLessons = completedLessons; currentUser.usedPromoCodes = usedPromoCodes; localStorage.setItem('grishaUser', JSON.stringify(currentUser)); } }
    function renderShop() { let html = '<div class="shop-grid">'; for (let [id, theme] of Object.entries(themes)) { const owned = purchasedItems.includes(id); const active = activeTheme === id; html += `<div class="shop-item"><strong>${theme.name}</strong><div>${active ? '✅' : owned ? '✓' : theme.price + ' 🪙'}</div>${!owned ? `<button data-action="buy" data-id="${id}" data-price="${theme.price}">Купить</button>` : (!active ? `<button data-action="activate" data-id="${id}">Выбрать</button>` : '')}</div>`; } html += '</div>'; document.getElementById('themeShop').innerHTML = html; }
    
    // Восстановлена старая распаковка: коробка с картинкой 📦 и надпись "нажми на коробку"
    function buildFirstLesson() {
        const c = document.getElementById('firstLessonContent');
        let html = '';
        if (selectedSituation === 'new') {
            html = '<p>🎉 Новый ноутбук! Нажми на коробку.</p><div id="boxContainer"><button id="magicBox" style="font-size:5rem; background:none; border:none; cursor:pointer;">📦</button></div><div id="stepsArea" style="display:none;"><div>💻✨</div><p>Подключи зарядку, включи, выбери язык, Wi-Fi, создай учётную запись, дождись рабочего стола.</p></div>';
        } else if (selectedSituation === 'used') {
            html = '<div>🔄💻</div><p><strong>Б/у ноутбук — проверка.</strong></p><ul><li>🔌 Проверь зарядку.</li><li>🔘 Нажми кнопку включения.</li><li>🔑 Узнай пароль.</li><li>🗑️ Удали чужие файлы.</li></ul>';
        } else {
            html = '<div>🏫👥</div><p><strong>Чужой ноутбук.</strong></p><ul><li>✋ Спроси разрешение.</li><li>🔘 Включи.</li><li>👤 Войди как гость.</li></ul>';
        }
        c.innerHTML = html;
        document.getElementById('goToCourseBtn').style.display = 'none';
        document.getElementById('skipToMenuBtn').style.display = 'none';
        const box = document.getElementById('magicBox');
        if (box) box.onclick = () => {
            document.getElementById('boxContainer').style.display = 'none';
            document.getElementById('stepsArea').style.display = 'block';
            document.getElementById('goToCourseBtn').style.display = '';
            document.getElementById('skipToMenuBtn').style.display = '';
        };
        if (selectedSituation !== 'new') {
            document.getElementById('goToCourseBtn').style.display = '';
            document.getElementById('skipToMenuBtn').style.display = '';
        }
    }

    function buildMainMenu() { const grid = document.getElementById('menuGrid'); grid.innerHTML = ''; const levelCourses = getCoursesForLevel(selectedLevel); levelCourses.forEach((course, i) => { const card = document.createElement('div'); card.className = 'menu-card' + (completedLessons[course.id] ? ' completed' : ''); card.textContent = course.title + (completedLessons[course.id] ? ' ✅' : ''); card.onclick = () => startCourse(i); grid.appendChild(card); }); }
    function startCourse(index) { const level = getCoursesForLevel(selectedLevel); if (!level || index >= level.length) { buildMainMenu(); showScreen(document.getElementById('mainMenuScreen')); return; } currentCourse = level[index]; currentSlideIndex = 0; document.getElementById('courseTitle').textContent = currentCourse.title; updateSlide(); showScreen(document.getElementById('courseScreen')); }
    function updateSlide() { document.getElementById('slideContent').innerHTML = currentCourse.slides[currentSlideIndex]; document.getElementById('slideProgress').style.width = ((currentSlideIndex + 1) / currentCourse.slides.length) * 100 + '%'; document.getElementById('prevSlideBtn').style.display = currentSlideIndex === 0 ? 'none' : ''; document.getElementById('nextSlideBtn').style.display = currentSlideIndex === currentCourse.slides.length - 1 ? 'none' : ''; document.getElementById('startQuizBtn').style.display = currentSlideIndex === currentCourse.slides.length - 1 ? '' : 'none'; }
    function startQuiz() { quizAnswers = new Array(currentCourse.quiz.length).fill(-1); quizSubmitted = false; let html = ''; currentCourse.quiz.forEach((q, idx) => { html += `<p><strong>${idx+1}. ${q.q}</strong></p>`; q.options.forEach((opt, oi) => html += `<div class="quiz-option" data-q="${idx}" data-opt="${oi}" id="opt_${idx}_${oi}">${opt}</div>`); }); document.getElementById('quizContent').innerHTML = html; document.getElementById('submitQuizBtn').style.display = ''; document.getElementById('quizResult').textContent = ''; document.getElementById('toMenuBtn').style.display = 'none'; document.querySelectorAll('.quiz-option').forEach(opt => opt.onclick = function() { if (quizSubmitted) return; const q = +this.dataset.q, o = +this.dataset.opt; quizAnswers[q] = o; document.querySelectorAll(`.quiz-option[data-q="${q}"]`).forEach(el => el.style.background = 'white'); this.style.background = '#f7e358'; }); showScreen(document.getElementById('quizScreen')); }
    function handlePromoCode() { if (!currentUser) { alert("Для использования промокода необходим аккаунт."); return; } let code = prompt("Промокод:"); if (!code) return; const norm = code.trim().toLowerCase(); const valid = { "газан69": 69, "кодразраба_0f8s7f9b2cd3": 99999 }; if (usedPromoCodes.includes(norm)) { alert("Промокод уже использован"); return; } if (valid[norm] !== undefined) { coins += valid[norm]; localStorage.setItem('grishaCoins', coins); usedPromoCodes.push(norm); saveUser(); updateBalance(); alert(`+${valid[norm]} монет`); } else alert("Неверный код"); }
    function deleteAccount() { if (!currentUser) return; if (confirm("Удалить аккаунт?")) { const users = JSON.parse(localStorage.getItem('grishaUsers') || '{}'); delete users[currentUser.name]; localStorage.setItem('grishaUsers', JSON.stringify(users)); currentUser = null; completedLessons = {}; usedPromoCodes = []; coins = 0; purchasedItems = ['default']; activeTheme = 'default'; localStorage.setItem('grishaCoins', '0'); localStorage.setItem('grishaPurchasedItems', JSON.stringify(purchasedItems)); localStorage.setItem('grishaActiveTheme', 'default'); applyTheme('default'); updateAuthUI(); showScreen(document.getElementById('welcomeScreen')); alert("Удалено"); hideSettingsModal(); } }
    function resetProgress() { if (confirm("Вы уверены что хотите бросить прогресс?")) { completedLessons = {}; coins = 0; localStorage.setItem('grishaCoins', '0'); if (currentUser) { currentUser.completedLessons = {}; currentUser.balance = 0; saveUser(); } updateBalance(); if (document.getElementById('mainMenuScreen').classList.contains('active')) buildMainMenu(); alert("Прогресс успешно сброшен"); hideSettingsModal(); } }
    function hideSettingsModal() { document.getElementById('settingsModal').classList.remove('active'); }
    
    document.getElementById('burgerBtn').onclick = () => document.getElementById('sidebar').classList.toggle('open');
    document.getElementById('settingsBtn').onclick = () => document.getElementById('settingsModal').classList.add('active');
    document.getElementById('closeSettingsBtn').onclick = hideSettingsModal;
    document.getElementById('infoSiteBtn').onclick = () => alert("Гриша — обучение компьютеру!");
    document.getElementById('promoCodeBtn').onclick = handlePromoCode;
    document.getElementById('deleteAccountBtn').onclick = deleteAccount;
    document.getElementById('resetProgressBtn').onclick = resetProgress;
    document.getElementById('startBtn').onclick = () => showScreen(document.getElementById('modelScreen'));
    document.querySelectorAll('#modelScreen .card-btn').forEach(b => b.onclick = function() { selectedModel = this.dataset.model; showScreen(document.getElementById('levelScreen')); });
    document.getElementById('backToWelcomeBtn').onclick = () => showScreen(document.getElementById('welcomeScreen'));
    document.querySelectorAll('#levelScreen .card-btn').forEach(b => b.onclick = function() { selectedLevel = this.dataset.level; if (selectedLevel === 'school') showScreen(document.getElementById('situationScreen')); else { selectedSituation = 'new'; buildFirstLesson(); showScreen(document.getElementById('firstLessonScreen')); } });
    document.getElementById('backToModelBtn').onclick = () => showScreen(document.getElementById('modelScreen'));
    document.querySelectorAll('#situationScreen .card-btn').forEach(b => b.onclick = function() { selectedSituation = this.dataset.situation; buildFirstLesson(); showScreen(document.getElementById('firstLessonScreen')); });
    document.getElementById('backToLevelBtn').onclick = () => showScreen(document.getElementById('levelScreen'));
    document.getElementById('backToSituationBtn').onclick = () => showScreen(selectedLevel === 'school' ? document.getElementById('situationScreen') : document.getElementById('levelScreen'));
    document.getElementById('goToCourseBtn').onclick = () => startCourse(0);
    document.getElementById('skipToMenuBtn').onclick = () => { buildMainMenu(); showScreen(document.getElementById('mainMenuScreen')); };
    document.getElementById('prevSlideBtn').onclick = () => { if (currentSlideIndex > 0) { currentSlideIndex--; updateSlide(); } };
    document.getElementById('nextSlideBtn').onclick = () => { if (currentSlideIndex < currentCourse.slides.length - 1) { currentSlideIndex++; updateSlide(); } };
    document.getElementById('startQuizBtn').onclick = startQuiz;
    document.getElementById('submitQuizBtn').onclick = () => { if (quizSubmitted) return; quizSubmitted = true; let correctCount = 0; currentCourse.quiz.forEach((q, idx) => { const ans = quizAnswers[idx], corr = q.correct; if (ans === corr) { correctCount++; document.getElementById(`opt_${idx}_${ans}`)?.classList.add('correct'); } else { if (ans >= 0) document.getElementById(`opt_${idx}_${ans}`)?.classList.add('wrong'); document.getElementById(`opt_${idx}_${corr}`)?.classList.add('correct'); } }); const passed = correctCount === currentCourse.quiz.length; document.getElementById('quizResult').textContent = passed ? '🎉 +10 монет' : `Правильно ${correctCount}/${currentCourse.quiz.length}`; document.getElementById('toMenuBtn').style.display = ''; document.getElementById('submitQuizBtn').style.display = 'none'; if (passed) { completedLessons[currentCourse.id] = true; coins += 10; localStorage.setItem('grishaCoins', coins); updateBalance(); saveUser(); } };
    document.getElementById('toMenuBtn').onclick = () => { buildMainMenu(); showScreen(document.getElementById('mainMenuScreen')); };
    document.getElementById('backToLevelFromMenuBtn').onclick = () => showScreen(document.getElementById('levelScreen'));
    
    // Авторизация
    document.getElementById('showLoginBtn').onclick = () => { document.getElementById('loginForm').style.display = 'block'; document.getElementById('registerForm').style.display = 'none'; };
    document.getElementById('showRegisterBtn').onclick = () => { document.getElementById('registerForm').style.display = 'block'; document.getElementById('loginForm').style.display = 'none'; };
    document.getElementById('cancelLoginBtn').onclick = () => document.getElementById('loginForm').style.display = 'none';
    document.getElementById('cancelRegisterBtn').onclick = () => document.getElementById('registerForm').style.display = 'none';
    document.getElementById('submitRegisterBtn').onclick = () => { const name = document.getElementById('regUsername').value.trim(); const pass = document.getElementById('regPassword').value.trim(); if (!name || !pass) { alert('Заполните'); return; } const users = JSON.parse(localStorage.getItem('grishaUsers') || '{}'); if (users[name]) { alert('Есть'); return; } users[name] = pass; localStorage.setItem('grishaUsers', JSON.stringify(users)); currentUser = { name, balance: 0, purchasedItems: ['default'], activeTheme: 'default', completedLessons: {}, usedPromoCodes: [] }; coins = 0; completedLessons = {}; usedPromoCodes = []; purchasedItems = ['default']; activeTheme = 'default'; saveUser(); updateAuthUI(); applyTheme('default'); document.getElementById('registerForm').style.display = 'none'; alert('Добро пожаловать!'); };
    document.getElementById('submitLoginBtn').onclick = () => { const name = document.getElementById('loginUsername').value.trim(); const pass = document.getElementById('loginPassword').value.trim(); const users = JSON.parse(localStorage.getItem('grishaUsers') || '{}'); if (!users[name] || users[name] !== pass) { alert('Неверно'); return; } const saved = localStorage.getItem('grishaUser'); if (saved && JSON.parse(saved).name === name) { const p = JSON.parse(saved); currentUser = p; coins = p.balance || 0; completedLessons = p.completedLessons || {}; purchasedItems = p.purchasedItems || ['default']; activeTheme = p.activeTheme || 'default'; usedPromoCodes = p.usedPromoCodes || []; } else { currentUser = { name, balance: 0, purchasedItems: ['default'], activeTheme: 'default', completedLessons: {}, usedPromoCodes: [] }; coins = 0; completedLessons = {}; usedPromoCodes = []; } localStorage.setItem('grishaCoins', coins); localStorage.setItem('grishaPurchasedItems', JSON.stringify(purchasedItems)); localStorage.setItem('grishaActiveTheme', activeTheme); applyTheme(activeTheme); updateAuthUI(); saveUser(); document.getElementById('loginForm').style.display = 'none'; alert('Вход выполнен'); };
    document.getElementById('logoutBtn').onclick = () => { currentUser = null; completedLessons = {}; usedPromoCodes = []; coins = 0; purchasedItems = ['default']; activeTheme = 'default'; localStorage.setItem('grishaCoins', '0'); localStorage.setItem('grishaPurchasedItems', JSON.stringify(purchasedItems)); localStorage.setItem('grishaActiveTheme', 'default'); applyTheme('default'); updateAuthUI(); showScreen(document.getElementById('welcomeScreen')); };
    document.getElementById('judgesFooterLink').onclick = () => { const p = prompt('Пароль:'); if (p === 'кванториум') window.location.href = "https://grisha-main.vercel.app/judges"; else if (p === '67') window.location.href = "https://youtu.be/yo5CILhgvT4?si=o3fOJvdXZUMKj8Ft"; else alert('Неверно'); };
    document.getElementById('themeShop').addEventListener('click', (e) => { const btn = e.target.closest('button'); if (!btn) return; const action = btn.dataset.action, id = btn.dataset.id; if (action === 'buy') { const price = +btn.dataset.price; if (coins >= price) { coins -= price; localStorage.setItem('grishaCoins', coins); purchasedItems.push(id); localStorage.setItem('grishaPurchasedItems', JSON.stringify(purchasedItems)); applyTheme(id); updateBalance(); updateAuthUI(); renderShop(); if(currentUser) saveUser(); } else alert('Недостаточно монет'); } else if (action === 'activate') { applyTheme(id); renderShop(); if(currentUser) saveUser(); } });
    
    applyTheme(activeTheme); updateBalance(); updateAuthUI(); renderShop();
})();